# .goreleaser.yaml
project_name: agglayer

release:
  disable: false
  draft: true
  prerelease: auto

builds:
  - id: linux-amd64
    main: ./cmd/
    binary: agglayer
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/0xPolygon/agglayer.Version={{ .Version }}
      - -X github.com/0xPolygon/agglayer.GitRev={{ .Commit }}
      - -X github.com/0xPolygon/agglayer.BuildDate={{ .Date }}
      - -X github.com/0xPolygon/agglayer.GitBranch={{ .Branch }}

  - id: linux-arm64
    main: ./cmd/
    binary: agglayer
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/0xPolygon/agglayer.Version={{ .Version }}
      - -X github.com/0xPolygon/agglayer.GitRev={{ .Commit }}
      - -X github.com/0xPolygon/agglayer.BuildDate={{ .Date }}
      - -X github.com/0xPolygon/agglayer.GitBranch={{ .Branch }}

  - main: ./cmd/
    binary: agglayer
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/0xPolygon/agglayer.Version={{ .Version }}
      - -X github.com/0xPolygon/agglayer.GitRev={{ .Commit }}
      - -X github.com/0xPolygon/agglayer.BuildDate={{ .Date }}
      - -X github.com/0xPolygon/agglayer.GitBranch={{ .Branch }}

archives:
  - files:
      - LICENSE.md
      - README.md

dockers:
  - image_templates:
      - 0xpolygon/{{ .ProjectName }}:{{ .Version }}-amd64
    dockerfile: Dockerfile.release
    use: buildx
    goos: linux
    goarch: amd64
    ids:
      - linux-amd64
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
    skip_push: false

  - image_templates:
      - 0xpolygon/{{ .ProjectName }}:{{ .Version }}-arm64
    dockerfile: Dockerfile.release
    use: buildx
    goos: linux
    goarch: arm64
    ids:
      - linux-arm64
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
    skip_push: false

docker_manifests:
  - name_template: 0xpolygon/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - 0xpolygon/{{ .ProjectName }}:{{ .Version }}-amd64
      - 0xpolygon/{{ .ProjectName }}:{{ .Version }}-arm64
    skip_push: false

  - name_template: 0xpolygon/{{ .ProjectName }}:latest
    image_templates:
      - 0xpolygon/{{ .ProjectName }}:{{ .Version }}-amd64
      - 0xpolygon/{{ .ProjectName }}:{{ .Version }}-arm64
    skip_push: false
