FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y \
    make \
    jq \
    git \
    yq \
    sudo

RUN apt-get update && \
    apt-get install -y \
    python3-pip && \
    pip3 install --no-cache-dir yq

WORKDIR /github/workspace