FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y \
    make \
    jq \
    git \
    yq \
    python3-pip \
    sudo

# Copies your code file from your action repository to the filesystem path `/` of the container
COPY cdk-build-script.sh /cdk-build-script.sh

# Executes `entrypoint.sh` when the Docker container starts up
ENTRYPOINT ["/cdk-build-script.sh"]