// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "1883a5f71424e6621daf6c1334ef539d"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"a3f86dc66303c9c136868faf93f5fb54": "1f8b08000000000000ff9492514fc2301485dffb2bee234430bc69c253d98a346e836c454563964a0b2eb296b49de8bf375b9d410218efdbcef9ceddc94dfb7db8288bb5e14e42a8770a85e9740659302131063a06f240339681753510e02cc0211922b41f9b6f519012cc481b6be0216a55864711f1e265a955e1b49122771f1675100080de2969a0993b9c06139c42326590cca3a8d7008580768e032ba3cb9c0b614e014e7fdb3f80d795564be9378724a0318e3a57d73d18740ff2ef7c531de5bc2db8e3bf0b7a7dcd6d5bfcecfa35b7f9d61475953f39bd5a59e94e711092319e470c063e515fbdb2674ef75a58a7cde71ef0f4ec9d978d5ebee5aa2a0146f48626cccb4b23b99322e70e188d49c6703c837bca26cd273c4e1372f08b6a2bfe9998a534c6e9026ec9023acdf3e84121baa83bfc0a0000ffff934d0191af020000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "./migrations")
		b.SetResolver("0001.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "a3f86dc66303c9c136868faf93f5fb54"})
	}()
	return nil
}()
